spring.application.name=lovelyshades
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lovelyshades;encrypt=false
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
