# =============================================
# PERFIL: dev
# =============================================

spring.application.name=lovelyshades

# --- SQL Server (acceso nativo, capa DAO) ---
sqlserver.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lovelyshades;encrypt=true;trustServerCertificate=true
sqlserver.datasource.username=sa
sqlserver.datasource.password=123456
sqlserver.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- JPA con SQL Server ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lovelyshades;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Swagger ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html